"""Presentation tests use synthetic source/text metadata, never game binaries."""
import copy
import importlib.util
import json
from pathlib import Path
import tempfile
import unittest

spec = importlib.util.spec_from_file_location("progress_modules", Path(__file__).resolve().parents[1] / "scripts/progress_modules.py")
mapper = importlib.util.module_from_spec(spec)
spec.loader.exec_module(mapper)


def measures(code, data=0, matched=0, units=1, complete=0):
    return {"totalCode": str(code), "matchedCode": str(matched), "completeCode": str(matched),
            "totalData": str(data), "matchedData": "0", "completeData": "0",
            "matchedCodePercent": matched / code * 100 if code else 0,
            "completeCodePercent": matched / code * 100 if code else 0,
            "matchedDataPercent": 0, "completeDataPercent": 0,
            "fuzzyMatchPercent": matched / (code + data) * 100 if code + data else 0,
            "totalUnits": units, "completeUnits": complete}


def function(program, source, name, address):
    item = {"name": name, "size": "4", "fuzzyMatchPercent": 100, "metadata": {"virtualAddress": str(address)}}
    return {"name": f"{program}/{source}/{name}", "functions": [item],
            "sections": [{**copy.deepcopy(item), "name": ".text"}], "measures": measures(4, matched=4, complete=1),
            "metadata": {"moduleName": program, "sourcePath": source, "complete": True,
                         "autoGenerated": False, "progressCategories": ["boot" if program == "boot" else "levels"]}}


def opaque(program, name, code, data=0):
    return {"name": program + "/" + name, "measures": measures(code, data),
            "sections": [{"name": name, "size": str(code + data), "fuzzyMatchPercent": 0, "metadata": {"virtualAddress": "8192"}}],
            "metadata": {"moduleName": program, "complete": False, "autoGenerated": True,
                         "progressCategories": ["boot" if program == "boot" else "levels"]}}


def report(units):
    code = sum(int(u["measures"]["totalCode"]) for u in units)
    data = sum(int(u["measures"]["totalData"]) for u in units)
    matched = sum(int(u["measures"]["matchedCode"]) for u in units)
    cats = []
    for parent in ("boot", "levels"):
        rows = [u for u in units if parent in u["metadata"]["progressCategories"]]
        cats.append({"id": parent, "name": parent, "measures": measures(
            sum(int(u["measures"]["totalCode"]) for u in rows), sum(int(u["measures"]["totalData"]) for u in rows),
            sum(int(u["measures"]["matchedCode"]) for u in rows), len(rows), sum(u["metadata"]["complete"] for u in rows))})
    return {"version": 2, "units": units, "measures": measures(code, data, matched, len(units), sum(u["metadata"]["complete"] for u in units)),
            "categories": cats}


class ModuleTests(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory()
        self.addCleanup(self.temp.cleanup)
        self.repo = Path(self.temp.name)
        self.layout = {"input_sha256": {}, "recipes": {}, "boot_modules": []}
        self.put("config/candidate-catalog.json", {"functions": []})
        self.put("config/level-catalog.json", {"levels": {}})
        data = '/* caf\u00e9: fake(void) { } */\nint fake(void);\nint first(void) { const char *s="}"; return 0; }\nint second(void) { return 1; }\n'
        self.recipe("candidates/boot.c", [("src/boot/words.cfrag", data, {})])
        self.put("config/candidate-catalog.json", {"functions": [{"symbol": "first", "address": 4096, "size": 4},
                                                                 {"symbol": "second", "address": 4100, "size": 4}]})
        self.layout["boot_modules"] = [{"fragment": "src/boot/words.cfrag", "name": "Observed word utilities"}]
        self.save_layout()
        self.input = report([function("boot", "candidates/boot.c", "first", 4096),
                             function("boot", "candidates/boot.c", "second", 4100),
                             opaque("boot", ".text-remainder", 40), opaque("boot", ".data", 0, 16)])

    def put(self, path, value):
        data = (json.dumps(value) + "\n").encode() if isinstance(value, dict) else value.encode()
        target = self.repo / path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(data)
        return data

    def recipe(self, source, pieces):
        data, rows = b"", []
        for path, text, replacements in pieces:
            raw = self.put(path, text)
            rendered = raw
            for key, value in replacements.items():
                rendered = rendered.replace(key.encode(), value.encode())
            rows.append({"fragment": path, "sha256": mapper.digest(raw), "source_text_bytes": len(raw), "replacements": replacements})
            data += rendered
        target = self.repo / source
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(data)
        self.layout["recipes"][source] = {"pieces": rows, "sha256": mapper.digest(data), "source_text_bytes": len(data)}

    def save_layout(self):
        self.put("config/source-layout.json", self.layout)

    def native(self, level, name, path=None, small=False):
        source = f"candidates/levels/{level}{'-g8' if small else ''}.c"
        fragment = path or "src/levels/shared/word.cfrag"
        self.recipe(source, [(fragment, "/* \u03bb */\nint @@FUNCTION@@(void) { return 0; }\n", {"@@FUNCTION@@": name})])
        self.put(f"config/{'level-g8' if small else 'level-native'}/{level}.json",
                 {"source": source, "program": "levels/" + level, "functions": [{"symbol": name, "address": 12288, "size": 4}]})
        self.save_layout()
        return function("levels/" + level, source, name, 12288)

    def test_exact_record_byte_measure_and_input_conservation(self):
        before = copy.deepcopy(self.input)
        grouped, summary = mapper.group_report(self.input, self.repo)
        self.assertEqual(self.input, before)
        for field, value in before["measures"].items():
            if field not in {"totalUnits", "completeUnits"}:
                self.assertEqual(grouped["measures"][field], value)
        self.assertEqual(summary["function_placements"], 2)
        self.assertEqual(summary["mapped_function_placements"], 2)
        modules = [u for u in grouped["units"] if u.get("functions")]
        self.assertEqual(len(modules), 1)
        self.assertEqual(modules[0]["functions"], [before["units"][0]["functions"][0], before["units"][1]["functions"][0]])
        self.assertEqual(modules[0]["sections"], [before["units"][0]["sections"][0], before["units"][1]["sections"][0]])
        self.assertEqual(modules[0]["metadata"]["sourcePath"], "src/boot/words.cfrag")
        self.assertIn("accepted subset", modules[0]["metadata"]["moduleName"])
        self.assertEqual([u for u in grouped["units"] if not u.get("functions")], sorted(before["units"][2:], key=lambda u: u["name"]))

    def test_replica_programs_and_native_g8_owners_are_not_deduplicated(self):
        units = [self.native("one", "one"), self.native("two", "two"), self.native("one", "small", "src/levels/shared/small.cfrag", True)]
        grouped, summary = mapper.group_report(report(units), self.repo)
        self.assertEqual(grouped["measures"]["matchedCode"], "12")
        self.assertEqual(len(grouped["units"]), 3)
        self.assertEqual({m["proof_owner"] for m in summary["modules"]}, {"level-native", "level-smalldata"})
        self.assertEqual({r["program"] for r in summary["lineage"]}, {"levels/one", "levels/two"})

    def test_level_denominator_includes_remainder_data_and_unresolved_source(self):
        known = self.native("one", "one")
        unknown = function("levels/one", "candidates/not-in-layout.c", "unknown", 4096)
        units = [known, unknown, opaque("levels/one", ".text-rest", 40), opaque("levels/one", ".data", 0, 16)]
        grouped, _ = mapper.group_report(report(units), self.repo)
        category = next(c for c in grouped["categories"] if c["id"] == "levels.level_one")
        self.assertEqual(category["measures"]["totalCode"], "48")
        self.assertEqual(category["measures"]["totalData"], "16")
        self.assertEqual(category["measures"]["matchedCode"], "8")
        self.assertLess(category["measures"]["matchedCodePercent"], 100)
        for old in units[2:]:
            actual = next(u for u in grouped["units"] if u["name"] == old["name"])
            actual = copy.deepcopy(actual)
            actual["metadata"]["progressCategories"].remove("levels.level_one")
            self.assertEqual(actual, old)

    def test_shared_boot_symbol_resolves_boot_fragment_with_overlay_address(self):
        self.put("config/level-catalog.json", {"levels": {"one": {"functions": [{"symbol": "first", "address": 16384, "size": 4}]}}})
        _, summary = mapper.group_report(report([function("levels/one", "candidates/boot.c", "first", 16384)]), self.repo)
        self.assertEqual(summary["lineage"][0]["proof_owner"], "boot-shared")
        self.assertEqual(summary["lineage"][0]["authored_source"], "src/boot/words.cfrag")

    def test_sdk_owner_is_explicit_catalogue_unit_id(self):
        self.recipe("candidates/sdk/sdk.c", [("src/sdk/sdk.c", "void sdk(void) {}\n", {})])
        self.put("config/boot-units/sdk.json", {"unit_id": "sdk-unit", "program": "boot", "source": "candidates/sdk/sdk.c",
                                               "functions": [{"symbol": "sdk", "address": 24576, "size": 4}]})
        self.save_layout()
        _, summary = mapper.group_report(report([function("boot", "candidates/sdk/sdk.c", "sdk", 24576)]), self.repo)
        self.assertEqual(summary["lineage"][0]["proof_owner"], "sdk-unit")

    def test_utf8_substitution_lengths_and_prototypes_do_not_steal_body(self):
        unit = self.native("one", "long_rendered_function_name")
        _, summary = mapper.group_report(report([unit]), self.repo)
        self.assertEqual(summary["mapped_function_placements"], 1)
        grouped, _ = mapper.group_report(self.input, self.repo)
        self.assertEqual(len(next(u for u in grouped["units"] if u.get("functions"))["functions"]), 2)

    def test_spanning_or_missing_definition_is_unknown_not_fake_module(self):
        self.recipe("candidates/boot.c", [("src/boot/header.cfrag", "int first(void) {\n", {}),
                                          ("src/boot/tail.cfrag", "return 0; }\n", {})])
        self.save_layout()
        grouped, summary = mapper.group_report(report(self.input["units"][:1]), self.repo)
        self.assertIsNone(summary["lineage"][0]["authored_source"])
        self.assertNotIn("sourcePath", grouped["units"][0]["metadata"])
        self.assertEqual(grouped["units"][0]["name"], self.input["units"][0]["name"])

    def test_fragment_candidate_and_pinned_input_hashes_are_enforced(self):
        self.put("src/boot/words.cfrag", "changed\n")
        with self.assertRaisesRegex(ValueError, "Stale authored"):
            mapper.group_report(self.input, self.repo)
        self.setUp()
        self.put("candidates/boot.c", "changed\n")
        with self.assertRaisesRegex(ValueError, "Generated source"):
            mapper.group_report(self.input, self.repo)
        self.setUp()
        self.layout["input_sha256"] = {"config/candidate-catalog.json": "0" * 64}
        self.save_layout()
        with self.assertRaisesRegex(ValueError, "Stale source-layout input"):
            mapper.group_report(self.input, self.repo)

    def assignment(self):
        desc = copy.deepcopy(mapper.DEFAULT)
        desc["assignments"] = [{"program": "boot", "symbol": "first", "address": 4096, "size": 4,
                                "source_path": "src/boot/words.cfrag", "source_sha256": mapper.digest((self.repo / "src/boot/words.cfrag").read_bytes()),
                                "role": "unclassified"}]
        return desc

    def test_role_orphan_stale_source_and_credit_override_are_rejected(self):
        for change in (lambda r: r.update(symbol="orphan"), lambda r: r.update(source_sha256="0" * 64),
                       lambda r: r.update(matchedCode=999), lambda r: r.update(source_path="../private.c")):
            with self.subTest(change=change):
                desc = self.assignment()
                change(desc["assignments"][0])
                with self.assertRaises(ValueError):
                    mapper.group_report(self.input, self.repo, desc)

    def test_unknown_roles_explicit_and_descriptor_does_not_edit_proof(self):
        grouped, summary = mapper.group_report(self.input, self.repo, self.assignment())
        self.assertEqual({r["role_id"] for r in summary["lineage"]}, {"unclassified"})
        self.assertEqual({r["role_confidence"] for r in summary["lineage"]}, {"unknown"})
        for unit in grouped["units"]:
            self.assertNotIn("roleConfidence", unit["metadata"])
        desc = copy.deepcopy(mapper.DEFAULT)
        desc["schema"] = True
        with self.assertRaises(ValueError):
            mapper.group_report(self.input, self.repo, desc)

    def test_private_role_paths_and_evidenceless_certainty_rejected(self):
        for label in ("/home/user/private", "/Users/person/notes", "/mnt/data", "See /root/notes", "C:/private", "\\\\server\\share"):
            with self.subTest(label=label):
                desc = copy.deepcopy(mapper.DEFAULT)
                desc["roles"]["example"] = {"label": label, "basis": "none", "confidence": "unknown"}
                with self.assertRaises(ValueError):
                    mapper.group_report(self.input, self.repo, desc)
        desc = copy.deepcopy(mapper.DEFAULT)
        desc["roles"]["example"] = {"label": "Some role", "basis": "none", "confidence": "reviewed"}
        with self.assertRaises(ValueError):
            mapper.group_report(self.input, self.repo, desc)

    def test_unqualified_retained_body_has_zero_credit_and_is_not_grouped(self):
        unit = copy.deepcopy(self.input["units"][0])
        unit["metadata"]["complete"] = False
        unit["measures"] = measures(4)
        unit["functions"][0]["fuzzyMatchPercent"] = 75
        grouped, summary = mapper.group_report(report([unit]), self.repo)
        self.assertEqual(grouped["units"], [unit])
        self.assertEqual(summary["function_placements"], 0)
        self.assertEqual(grouped["measures"]["matchedCode"], "0")

    def test_forged_complete_partial_unit_is_rejected_not_promoted(self):
        self.input["units"][0]["measures"]["matchedCode"] = "0"
        with self.assertRaisesRegex(ValueError, "cannot promote"):
            mapper.group_report(self.input, self.repo)

    def test_deterministic_order_and_read_only_repository(self):
        before = {p.relative_to(self.repo): p.read_bytes() for p in self.repo.rglob("*") if p.is_file()}
        first = mapper.group_report(self.input, self.repo)
        shuffled = copy.deepcopy(self.input)
        shuffled["units"].reverse()
        second = mapper.group_report(shuffled, self.repo)
        self.assertEqual(first, second)
        self.assertEqual(before, {p.relative_to(self.repo): p.read_bytes() for p in self.repo.rglob("*") if p.is_file()})


if __name__ == "__main__":
    unittest.main()
